spring:
  cloud:
    openfeign:
      client:
        config:
          default:  # 默认配置
            logger-level: full  # 日志级别
            connect-timeout: 1000  # 连接超时时间
            read-timeout: 2000  # 读取超时时间
          service-product:  # 单独给某个feign Client 配置，我们这里是配置商品的feign
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
#            request-interceptors:
#              - com.star.interceptor.XTokenRequestInterceptor
#            retryer: feign.retryer.Default

    sentinel:  # 配置sentinel
      transport:
        dashboard: localhost:9999  # 默认sentinel-dashboard的端口为8080,这里我是改的端口为9999
      eager: true  # 提前加载，服务一启动，就连接到sentinel控制台
      web-context-unify: false  # 不统一web的上下文（分割请求链路）



feign:
  sentinel:
    enabled: true  # 开启服务熔断，feign远程调用失败之后会走兜底回调方法
