spring:
  cloud:
    openfeign:
      client:
        config:
          default:  # 默认配置
            logger-level: full  # 日志级别
            connect-timeout: 1000  # 连接超时时间
            read-timeout: 2000  # 读取超时时间
          service-product:  # 单独给某个feign Client 配置，我们这里是配置商品的feign
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
feign:
  sentinel:
    enabled: true  # 开启服务熔断，feign远程调用失败之后会走兜底回调方法
